### ISSUE TITLE
refineOcculterSlews enters findAllowableOcculterSlews even if sotoStarshade isn't used

### ISSUE THREAD

**Issue by walker-dula** [dsavransky/EXOSIMS#187]
**Describe the bug**
I am running the TS_DD and noticed that if even if we are not using the sotoStarshade Observatory module, we still call findAllowableOcculterSlews instead of filterOcculterSlews:

```
        # slew times were calculated/decided beforehand (Observatory Prototype)
        if all( abs(switch) > 1*u.min ):
            sInds, intTimes, slewTimes = self.filterOcculterSlews(sInds, slewTimes[sInds], \
                                                obsTimeArray[sInds,:], intTimeArray[sInds,:], mode)
            dV = np.zeros(len(sInds))*u.m/u.s
        
        # slew times have not been calculated/decided yet (SotoStarshade)
        else:
            sInds,intTimes,slewTimes,dV = self.findAllowableOcculterSlews(sInds, old_sInd, sd[sInds], \
                                                slewTimes[sInds], obsTimeArray[sInds,:], intTimeArray[sInds,:], mode)
```

This results in the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/EXOSIMS/EXOSIMS/SurveySimulation/tieredScheduler_DD.py", line 72, in run_sim
    DRM, sInd, occ_sInd, t_det, sd, occ_sInds, det_mode = self.next_target(sInd, occ_sInd, det_modes, char_mode)
  File "/proj/EXOSIMS/EXOSIMS/SurveySimulation/tieredScheduler_DD.py", line 430, in next_target
    char_mode)  
  File "/proj/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.py", line 815, in refineOcculterSlews
    slewTimes[sInds], obsTimeArray[sInds,:], intTimeArray[sInds,:], mode)
  File "/proj/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.py", line 1081, in findAllowableOcculterSlews
    allowed_dVs[dV_inds,:], allowedintTimes[filterDuds,:], allowedCharTimes[filterDuds,:])
  File "/Users/wdula/Documents/astropy-2.0.6/astropy/units/quantity.py", line 1153, in __getitem__
    out = super(Quantity, self).__getitem__(key)
```

The specific problem is that allowed_dVs  in allowed_dVs[dV_inds,:] is not the correct size, having not been calculated using sotoStarshade. It is a 1D array, instead of the expected 2D array.

**To Reproduce**
You can reproduce this behavior by running EXOSIMS using the 
```
/proj/exep/rhonda/Sandbox/HabEx/Scripts/HabEx_4m_TSDD_maxvisit10_5384_20181114.json
```
scriptfile. The bug typically triggers several hundred observations into the sim.

**EXOSIMS version:**
 - master branch

**Comment by dsavransky** [comment]
@walker-dula @gjsoto please confirm that this issue can be closed.

**Comment by walker-dula** [comment]
I believe this issue has been dealt with and can be closed.
