### ISSUE TITLE
HabEx Target List filtering to 0?

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#227]
Under branch purpleCobra, running vanilla HabEx script w/o starshade produces the following error once the total observing time is sufficiently large. (discovered when running various mission Life - mission portion parameters)

length "missionLife": 10.0,  "missionPortion": 0.195, ran successfully
length "missionLife": 10.0, "missionPortion": 0.225, failed
Scripts identical otherwise

Error Log:
ValueError('zero-size array to reduction operation minimum which has no identity',)
Traceback (most recent call last):
  File "/home/drk94/Documents/exosims/EXOSIMS/EXOSIMS/run/runQueue.py", line 50, in run_one
    SS.run_sim()
  File "/home/drk94/Documents/exosims/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.py", line 390, in run_sim
    DRM, sInd, det_intTime, waitTime = self.next_target(sInd, det_mode)
  File "/home/drk94/Documents/exosims/EXOSIMS/EXOSIMS/Prototypes/SurveySimulation.py", line 636, in next_target
    sInd, waitTime = self.choose_next_target(old_sInd, sInds, slewTimes, intTimes[sInds])
  File "/home/drk94/Documents/exosims/EXOSIMS/EXOSIMS/SurveySimulation/SLSQPScheduler.py", line 493, in choose_next_target
    timeToAdvance = np.min(np.asarray(timefZminAfterNow))#find the minimum time
  File "/opt/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2442, in amin
    initial=initial)
  File "/opt/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by deanthedream** [comment]
I think this is related to the error Rhonda experienced with her script filtering the number of target stars to 0....
