### ISSUE TITLE
VOtable import may be out of date with exported VOtables

### ISSUE THREAD

**Issue by turmon** [dsavransky/EXOSIMS#329]
**Is your feature request related to a problem? Please describe.**

Following the instructions at class KnownRVPlanets(KeplerLike1)
[which, side issue, need to be updated - link rot]
I downloaded a new VOtable from the exoplanet archive.
The URL I used is a the first recommended redirect from the exoplanet archive link in the instructions. The Exoplanet archive redirect page labels the link I used as
 (Confirmed Planets or Extended Planet Data)  

It points to this URL:
https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PS

I followed the rest of the directions to get a VOtable.

The second recommended link ("Composite Parameters") allows a similar download, but this table also causes an attribute-name mismatch.

In either case, the field names seem to have changed. E.g., there is no pl_host on this table, and the magnitude fields have changed names, and so on.

**Describe the solution you'd like**
Probably we need to keep up-to-date with the current naming scheme, unless there's more than one VOtable naming scheme, and I can select a compatible one.

**Additional context**

**Comment by turmon** [comment]
Modules fragment to reproduce:

  "modules": {
    "PlanetPopulation": "KnownRVPlanets",
    "StarCatalog": " ",
    "OpticalSystem": "Nemati",
    "ZodiacalLight": " ",
    "BackgroundSources": "GalaxiesFaintStars",
    "PlanetPhysicalModel": " ",
    "Observatory": "WFIRSTObservatoryL2",
    "TimeKeeping": " ",
    "PostProcessing": " ",
    "Completeness": " ",
    "TargetList": "KnownRVPlanetsTargetList",
    "SimulatedUniverse": "KnownRVPlanetsUniverse",
    "SurveySimulation": " ",
    "SurveyEnsemble": " "
  }

-------------------


Traceback (most recent call last):
  File "/proj/exep/rhonda/Sandbox/HabEx/Analyses/integration-time/./test_OpticalSystem_int_time.py", line 316, in test_char_750nm
    self.run_one_test(scenario, mode_num, mode_name, exosims_to_reference_char)
  File "/proj/exep/rhonda/Sandbox/HabEx/Analyses/integration-time/./test_OpticalSystem_int_time.py", line 334, in run_one_test
    self.setUp_simulation(scenario)
  File "/proj/exep/rhonda/Sandbox/HabEx/Analyses/integration-time/./test_OpticalSystem_int_time.py", line 280, in setUp_simulation
    SU = load_universe(scenario)
  File "/proj/exep/rhonda/Sandbox/HabEx/Analyses/integration-time/./test_OpticalSystem_int_time.py", line 257, in load_universe
    SU = SU_mod(**specs)
  File "/proj/exep/rhonda/Sandbox/EXOSIMS-versions/Photometry2022/EXOSIMS/EXOSIMS/SimulatedUniverse/KnownRVPlanetsUniverse.py", line 21, in __init__
    SimulatedUniverse.__init__(self, **specs)
  File "/proj/exep/rhonda/Sandbox/EXOSIMS-versions/Photometry2022/EXOSIMS/EXOSIMS/Prototypes/SimulatedUniverse.py", line 205, in __init__
    self.TargetList = get_module(specs["modules"]["TargetList"], "TargetList")(
  File "/proj/exep/rhonda/Sandbox/EXOSIMS-versions/Photometry2022/EXOSIMS/EXOSIMS/TargetList/KnownRVPlanetsTargetList.py", line 64, in __init__
    TargetList.__init__(self, **specs)
  File "/proj/exep/rhonda/Sandbox/EXOSIMS-versions/Photometry2022/EXOSIMS/EXOSIMS/Prototypes/TargetList.py", line 385, in __init__
    self.populate_target_list(**specs)
  File "/proj/exep/rhonda/Sandbox/EXOSIMS-versions/Photometry2022/EXOSIMS/EXOSIMS/TargetList/KnownRVPlanetsTargetList.py", line 123, in populate_target_list
    dist = tmp["st_dist"].filled() * u.pc
  File "/usr/local/anaconda3/envs/cornell-v2/lib/python3.10/site-packages/numpy/ma/core.py", line 3224, in __getitem__
    dout = self.data[indx]
ValueError: no field of name st_dist

==> Similar error when looking for pl_hostname, Vmag, etc.

**Comment by dsavransky** [comment]
The IPAC tables have been changed upstream and the KnownRV family of modules is being deprecated and replaced with the plandb family of modules (currently in development).
