### ISSUE TITLE
Apparent caching bug noted regarding missionLife, keepout, and Zodi

### ISSUE THREAD

**Issue by dsavransky** [dsavransky/EXOSIMS#371]
Reported by @turmon:

I changed the missionLife of a working script from 10 to 1.1 for a test, and found﻿ a possible caching bug.

The interaction is that the zodi minimum is found in ZodiacalLight Prototype like so:

        for i in range(len(sInds)):
            tmpfZmin = min(fZmins[i, :])  # fZ_matrix has dimensions sInds

            if tmpfZmin == sys.float_info.max:
                valfZmin[i] = np.nan
                absTimefZmin[i] = -1
            else:
                valfZmin[i] = tmpfZmin
                indfZmin = np.argmin(fZmins[i, :])  # Gets indices where fZmin occurs
                absTimefZmin[i] = koTimes[indfZmin].value

But the koTimes is now "short" (1.1 years) because I changed missionLife. So, koTimes has length 402, while indfZmin happens to be 580. And then we look 580 up in koTimes, and it's not the right size.

Here's the traceback.

Note in the PDB session afterwards that koTimes.shape < indfZmin.
And fZmins.shape is the original 10-years long (3653).

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/cornell-v2/lib/python3.10/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/anaconda3/envs/cornell-v2/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/local/anaconda3/envs/cornell-v2/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/proj/exep/rhonda/Sandbox/HabEx/Local/ipcluster_ensemble_jpl_driver.py", line 425, in <module>
    message = main(args, xspecs)
  File "/proj/exep/rhonda/Sandbox/HabEx/Local/ipcluster_ensemble_jpl_driver.py", line 336, in main
    res = sim.run_ensemble(int(args.numruns), run_one=run_one, kwargs=kwargs)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/MissionSim.py", line 369, in run_ensemble
    res = self.SurveyEnsemble.run_ensemble(
  File "/proj/exep/rhonda/Sandbox/HabEx/Local/EXOSIMS_local/IPClusterEnsembleJPL2.py", line 108, in run_ensemble
    return self.run_ensemble_stand(sim, nb_run_sim, run_one, genNewPlanets, rewindPlanets, kwargs)
  File "/proj/exep/rhonda/Sandbox/HabEx/Local/EXOSIMS_local/IPClusterEnsembleJPL2.py", line 126, in run_ensemble_stand
    ar = run_one(genNewPlanets=genNewPlanets, rewindPlanets=rewindPlanets, **kwargs)
  File "/proj/exep/rhonda/Sandbox/HabEx/Local/ipcluster_ensemble_jpl_driver.py", line 209, in run_one
    SS.reset_sim(genNewPlanets=genNewPlanets, rewindPlanets=rewindPlanets)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/Prototypes/SurveySimulation.py", line 2385, in reset_sim
    self.__init__(**specs)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/SurveySimulation/tieredScheduler_DD.py", line 19, in __init__
    tieredScheduler.__init__(self, **specs)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/SurveySimulation/tieredScheduler.py", line 92, in __init__
    SurveySimulation.__init__(self, **specs)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/Prototypes/SurveySimulation.py", line 457, in __init__
    self.valfZmin, self.absTimefZmin = self.ZodiacalLight.extractfZmin(
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/Prototypes/ZodiacalLight.py", line 495, in extractfZmin
    absTimefZmin[i] = koTimes[indfZmin].value
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/astropy/utils/shapes.py", line 225, in __getitem__
    return self._apply("__getitem__", item)
  File "/proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/astropy/time/core.py", line 1273, in _apply
    jd1 = apply_method(jd1)
IndexError: index 580 is out of bounds for axis 0 with size 402
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/astropy/time/core.py(1273)_apply()
-> jd1 = apply_method(jd1)

(Pdb) up
> /proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/astropy/utils/shapes.py(225)__getitem__()
-> return self._apply("__getitem__", item)
(Pdb) up
> /proj/exep/rhonda/Sandbox/Python-venvs/exosims-3.2.0/lib/python3.10/site-packages/EXOSIMS/Prototypes/ZodiacalLight.py(495)extractfZmin()
-> absTimefZmin[i] = koTimes[indfZmin].value
(Pdb) indfZmin
580
(Pdb) koTimes.shape
(402,)
(Pdb) fZmins.shape
(714, 3653)
(Pdb)

**Comment by CoreySpohn** [comment]
I ran into this too. The easiest fix seems to be changing `modeHashName` in SurveySimulation from
```
modeHashName =f'{self.cachefname[0:-1]}_{TL.nStars}_{mode["syst"]["name"]}.'
```
to 
```
modeHashName = f'{self.cachefname[0:-1]}_{TL.nStars}_{mode["syst"]["name"]}_{startTime.mjd:0}_{endTime.mjd:0}.'
```
that way it doesn't end up with the array length mismatch that causes the error. I didn't test this, but it seems like when you increase your mission lifetime and pull fZ values from a shorter one you may never have an error but may get incorrect values being used (e.g. when the mission is past the last time of the shorter mission). Ideally you'd want a better system to reuse fZ values which I guess could be done by parsing the saved files to check if the current mission length is a subset of one of the cached fZ files.

**Comment by dsavransky** [comment]
Closed by #408
